/*
* generated by Xtext
*/
package org.xtext.example.checkerdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.checkerdsl.services.CheckerDslGrammarAccess;

public class CheckerDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CheckerDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.checkerdsl.parser.antlr.internal.InternalCheckerDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.checkerdsl.parser.antlr.internal.InternalCheckerDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Dsl";
	}
	
	public CheckerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CheckerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
