/*
 * generated by Xtext
 */
package org.xtext.example.checkerdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.checkerdsl.ui.internal.CheckerDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CheckerDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CheckerDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CheckerDslActivator.getInstance().getInjector(CheckerDslActivator.ORG_XTEXT_EXAMPLE_CHECKERDSL_CHECKERDSL);
	}
	
}
