/**
 * generated by Xtext
 */
package org.xtext.example.checkerdsl.generator;

import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.checkerdsl.checkerDsl.Property;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class CheckerDslGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Property> _filter = Iterators.<Property>filter(_allContents, Property.class);
    final Function1<Property, String> _function = new Function1<Property, String>() {
      public String apply(final Property it) {
        return it.getType();
      }
    };
    Iterator<String> _map = IteratorExtensions.<Property, String>map(_filter, _function);
    String _plus = (("import java.io.*;\n" + 
      "import java.util.*;\n") + _map);
    fsa.generateFile("IOClass.java", _plus);
  }
}
