/*
 * generated by Xtext
 */
package org.xtext.example.checkerdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CheckerDslUiModule extends org.xtext.example.checkerdsl.ui.AbstractCheckerDslUiModule {
	public CheckerDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
