/*
 * generated by Xtext
 */
package org.xtext.example.checkerdsl.ui.contentassist

import org.xtext.example.checkerdsl.ui.contentassist.AbstractCheckerDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CheckerDslProposalProvider extends AbstractCheckerDslProposalProvider {
}
