/*
* generated by Xtext
*/
package org.xtext.example.checkerdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CheckerDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.checkerdsl.ui.internal.CheckerDslActivator.getInstance().getInjector("org.xtext.example.checkerdsl.CheckerDsl");
	}
	
}
