/**
 * generated by Xtext
 */
package org.xtext.example.checkerdsl.validation;

import org.xtext.example.checkerdsl.validation.AbstractCheckerDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CheckerDslValidator extends AbstractCheckerDslValidator {
}
