/*
* generated by Xtext
*/
package org.xtext.example.checkerdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CheckerDslStandaloneSetup extends CheckerDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CheckerDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

